// This file is auto-generated from assets/manifest/assets_manifest.json.
// Do not edit by hand; run `python scripts/generate_asset_index.py` instead.

export const GENERATED_ASSETS = Object.freeze({
  bg_deep_space_main: "assets/final/backgrounds/bg_deep_space_main.png",
  bg_nebula_blue: "assets/final/backgrounds/bg_nebula_blue.png",
  effect_large_explosion: "assets/final/effects/effect_large_explosion.png",
  effect_planet_range_inner_danger: "assets/final/effects/effect_planet_range_inner_danger.png",
  effect_planet_range_middle_basic: "assets/final/effects/effect_planet_range_middle_basic.png",
  effect_planet_range_outer_basic: "assets/final/effects/effect_planet_range_outer_basic.png",
  effect_ship_evolution_burst: "assets/final/effects/effect_ship_evolution_burst.png",
  effect_small_explosion: "assets/final/effects/effect_small_explosion.png",
  effect_station_warp: "assets/final/effects/effect_station_warp.png",
  effect_thruster_flame_basic: "assets/final/effects/effect_thruster_flame_basic.png",
  enemy_basic_small_ship: "assets/final/enemies/enemy_basic_small_ship.png",
  enemy_drone: "assets/final/enemies/enemy_drone.png",
  enemy_elite_cruiser: "assets/final/enemies/enemy_elite_cruiser.png",
  enemy_gunboat: "assets/final/enemies/enemy_gunboat.png",
  enemy_kamikaze_ship: "assets/final/enemies/enemy_kamikaze_ship.png",
  enemy_mini_fleet: "assets/final/enemies/enemy_mini_fleet.png",
  enemy_mother_guardian: "assets/final/enemies/enemy_mother_guardian.png",
  enemy_phase_wraith: "assets/final/enemies/enemy_phase_wraith.png",
  enemy_poison_sac: "assets/final/enemies/enemy_poison_sac.png",
  enemy_shielded_brute: "assets/final/enemies/enemy_shielded_brute.png",
  enemy_swarm_bug: "assets/final/enemies/enemy_swarm_bug.png",
  enemy_turret_satellite: "assets/final/enemies/enemy_turret_satellite.png",
  env_asteroid_basic: "assets/final/environment/env_asteroid_basic.png",
  env_black_hole: "assets/final/environment/env_black_hole.png",
  env_distant_planet: "assets/final/environment/env_distant_planet.png",
  env_energy_storm: "assets/final/environment/env_energy_storm.png",
  env_fleet_wreckage: "assets/final/environment/env_fleet_wreckage.png",
  env_ore_chunk: "assets/final/environment/env_ore_chunk.png",
  env_poison_fog: "assets/final/environment/env_poison_fog.png",
  env_space_rift: "assets/final/environment/env_space_rift.png",
  planet_core_basic: "assets/final/planets/planet_core_basic.png",
  planet_electromagnetic_storm: "assets/final/planets/planet_electromagnetic_storm.png",
  planet_fire_war: "assets/final/planets/planet_fire_war.png",
  planet_hive_breeding: "assets/final/planets/planet_hive_breeding.png",
  planet_machine_foundry: "assets/final/planets/planet_machine_foundry.png",
  planet_rock_mining: "assets/final/planets/planet_rock_mining.png",
  planet_state_suppressed: "assets/final/planets/planet_state_suppressed.png",
  planet_void_rift: "assets/final/planets/planet_void_rift.png",
  resource_bio_sample: "assets/final/resources/resource_bio_sample.png",
  resource_black_box: "assets/final/resources/resource_black_box.png",
  resource_credits: "assets/final/resources/resource_credits.png",
  resource_energy_battery: "assets/final/resources/resource_energy_battery.png",
  resource_exp_orb: "assets/final/resources/resource_exp_orb.png",
  resource_metal_ore: "assets/final/resources/resource_metal_ore.png",
  resource_repair_kit: "assets/final/resources/resource_repair_kit.png",
  resource_shield_fragment: "assets/final/resources/resource_shield_fragment.png",
  resource_star_core: "assets/final/resources/resource_star_core.png",
  resource_void_charge: "assets/final/resources/resource_void_charge.png",
  resource_weapon_chip: "assets/final/resources/resource_weapon_chip.png",
  ship_player_t1_explorer: "assets/final/ships/ship_player_t1_explorer.png",
  ship_player_t2_scout: "assets/final/ships/ship_player_t2_scout.png",
  ship_player_t3_fighter: "assets/final/ships/ship_player_t3_fighter.png",
  ship_player_t4_gunboat: "assets/final/ships/ship_player_t4_gunboat.png",
  ship_player_t5_cruiser: "assets/final/ships/ship_player_t5_cruiser.png",
  ship_player_t6_super: "assets/final/ships/ship_player_t6_super.png",
  ship_state_player_hit: "assets/final/effects/ship_state_player_hit.png",
  ship_state_player_shield: "assets/final/effects/ship_state_player_shield.png",
  station_portal: "assets/final/stations/station_portal.png",
  station_repair_bay: "assets/final/stations/station_repair_bay.png",
  station_rest_basic: "assets/final/stations/station_rest_basic.png",
  station_shop_terminal: "assets/final/stations/station_shop_terminal.png",
  station_starmap_bg: "assets/final/stations/station_starmap_bg.png",
  station_upgrade_terminal: "assets/final/stations/station_upgrade_terminal.png",
  ui_icon_danger_level: "assets/final/ui/ui_icon_danger_level.png",
  ui_icon_hp: "assets/final/ui/ui_icon_hp.png",
  ui_icon_kill: "assets/final/ui/ui_icon_kill.png",
  ui_icon_level: "assets/final/ui/ui_icon_level.png",
  ui_icon_minimap: "assets/final/ui/ui_icon_minimap.png",
  ui_icon_planet_threat: "assets/final/ui/ui_icon_planet_threat.png",
  ui_icon_planet_type: "assets/final/ui/ui_icon_planet_type.png",
  ui_icon_resource: "assets/final/ui/ui_icon_resource.png",
  ui_icon_rest_station: "assets/final/ui/ui_icon_rest_station.png",
  ui_icon_rest_station_marker: "assets/final/ui/ui_icon_rest_station_marker.png",
  ui_icon_shield: "assets/final/ui/ui_icon_shield.png",
  ui_icon_star_region: "assets/final/ui/ui_icon_star_region.png",
  ui_icon_timer: "assets/final/ui/ui_icon_timer.png",
  ui_icon_upgrade: "assets/final/ui/ui_icon_upgrade.png",
  ui_icon_warning: "assets/final/ui/ui_icon_warning.png",
  ui_icon_weapon: "assets/final/ui/ui_icon_weapon.png",
  ui_icon_xp: "assets/final/ui/ui_icon_xp.png",
  weapon_chain_lightning: "assets/final/weapons/weapon_chain_lightning.png",
  weapon_drone_shot: "assets/final/weapons/weapon_drone_shot.png",
  weapon_gravity_field: "assets/final/effects/weapon_gravity_field.png",
  weapon_homing_missile: "assets/final/weapons/weapon_homing_missile.png",
  weapon_laser_basic: "assets/final/weapons/weapon_laser_basic.png",
  weapon_laser_beam: "assets/final/weapons/weapon_laser_beam.png",
  weapon_plasma_cannon: "assets/final/weapons/weapon_plasma_cannon.png",
  weapon_scatter_shot: "assets/final/weapons/weapon_scatter_shot.png",
  weapon_shield_pulse: "assets/final/effects/weapon_shield_pulse.png",
});

export function getGeneratedAssetPath(assetId) {
  return GENERATED_ASSETS[assetId] ?? null;
}
