import Phaser from 'phaser';
import './styles.css';

const ASSETS=['ship_player','enemy_low','enemy_mid','enemy_high','planet_low','planet_mid','planet_high','planet_neutral','coin','xp','tech','weapon_laser','weapon_missile','weapon_drone','weapon_shield','weapon_emp','weapon_blackhole','black_box','civ_hive','civ_machine','civ_crystal','civ_gravity','civ_void','civ_time','civ_core'];
const CIVS=['虫巢母星','机械母星','水晶母星','引力母星','虚空母星','时间母星','深空核心'];
const state={mode:'menu',day:1,kills:0,planets:0,level:1,xp:0,coins:0,tech:0,dead:false,dock:false,upgrade:false,blackBoxRecovered:false};
const saveKey='lost-deep-space-drifter-save-v1';
const save=JSON.parse(localStorage.getItem(saveKey)||'{"bestDay":0,"bestKills":0,"blackBoxes":0,"permanent":{"hp":0,"shield":0,"attack":0,"radar":0}}');
const app=document.querySelector('#app');
app.innerHTML='<canvas id="game"></canvas><div class="hint">WASD / 方向键移动 · 自动攻击 · 手机可拖动左下虚拟摇杆</div>';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
new Phaser.Game({title:'Lost Deep Space: Drifter',type:Phaser.AUTO});
let W=0,H=0,keys={},touch=null,last=0,shoot=0,player,planets=[],enemies=[],loot=[],shots=[],menuStars=[];
function imgUrl(n){return new URL('../assets/'+n+'.svg',import.meta.url).href}
function resize(){W=canvas.width=innerWidth*devicePixelRatio;H=canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key==='Enter'&&state.mode==='menu')start()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
canvas.addEventListener('pointerdown',e=>{const x=e.clientX,y=e.clientY;if(state.mode==='menu'){start();return}clickUi(x,y);if(x<170&&y>innerHeight-170)touch={id:e.pointerId,x,y,dx:0,dy:0}});canvas.addEventListener('pointermove',e=>{if(touch&&touch.id===e.pointerId){touch.dx=e.clientX-touch.x;touch.dy=e.clientY-touch.y}});canvas.addEventListener('pointerup',e=>{if(touch&&touch.id===e.pointerId)touch=null});
function resetWorld(){Object.assign(state,{mode:'play',day:1,kills:0,planets:0,level:1,xp:0,coins:0,tech:0,dead:false,dock:false,upgrade:false,blackBoxRecovered:false});player={x:0,y:0,hp:120+save.permanent.hp*20,maxHp:120+save.permanent.hp*20,shield:60+save.permanent.shield*10,maxShield:60+save.permanent.shield*10,speed:220,attack:18+save.permanent.attack*4,radar:900+save.permanent.radar*80,magnet:120,weapons:['自动激光','追踪导弹','环绕无人机','能量护盾','电磁脉冲','黑洞炸弹']};planets=[];enemies=[];loot=[];shots=[];for(let i=-3;i<=3;i++)for(let j=-3;j<=3;j++)spawnPlanet(i,j);planets.push({x:180,y:80,r:58,type:'neutral',name:'晨星港'});if(save.blackBox)loot.push({x:save.blackBox.x,y:save.blackBox.y,r:22,type:'black_box',value:save.blackBox.coins||20});}
function start(){resetWorld()}function spawnPlanet(i,j){const seed=Math.sin(i*91+j*37)*9999,rx=(seed%1)*420,ry=((seed*7)%1)*420;const types=['low','mid','high'];const type=(Math.abs(i)+Math.abs(j))%11===0?'neutral':types[Math.abs(Math.floor(seed*3))%3];planets.push({x:i*820+rx,y:j*820+ry,r:type==='neutral'?54:70,type,name:type==='neutral'?'中立星港':type==='low'?'低等星球':type==='mid'?'中等星球':'高等星球',angry:false});}
function update(dt){if(state.mode!=='play'||state.upgrade||state.dock)return;state.day+=dt/60;let ax=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),ay=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);if(touch){ax=Phaser.Math.Clamp(touch.dx/55,-1,1);ay=Phaser.Math.Clamp(touch.dy/55,-1,1)}const len=Math.hypot(ax,ay)||1;player.x+=ax/len*player.speed*dt;player.y+=ay/len*player.speed*dt;for(const p of planets){const d=Math.hypot(player.x-p.x,player.y-p.y);if(d<player.radar&&!p.seen){p.seen=true;state.planets++}if(p.type==='neutral'&&d<p.r+80)state.dockPrompt=true;else if(p.type!=='neutral'&&d<p.r+230&&!p.angry){p.angry=true;for(let k=0;k<5+(p.type==='high'?5:0);k++)spawnEnemy(p)}}if(!planets.some(p=>p.type==='neutral'&&Math.hypot(player.x-p.x,player.y-p.y)<p.r+80))state.dockPrompt=false;if(state.day>3&&Math.random()<dt*.7)spawnEnemy({x:player.x+700-Math.random()*1400,y:player.y+700-Math.random()*1400,type:'high'});for(const e of enemies){const a=Math.atan2(player.y-e.y,player.x-e.x);e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt;if(Math.hypot(player.x-e.x,player.y-e.y)<28){player.shield-=e.damage*dt;if(player.shield<0){player.hp+=player.shield;player.shield=0}}}shoot-=dt;if(shoot<=0){autoAttack();shoot=.35}for(const s of shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;for(const e of enemies)if(e.hp>0&&Math.hypot(s.x-e.x,s.y-e.y)<24){e.hp-=s.damage;s.life=0}}shots=shots.filter(s=>s.life>0);for(const e of enemies.filter(e=>e.hp<=0)){state.kills++;drop(e);enemies.splice(enemies.indexOf(e),1)}for(const l of loot){const d=Math.hypot(player.x-l.x,player.y-l.y);if(d<player.magnet){l.x+=(player.x-l.x)*dt*4;l.y+=(player.y-l.y)*dt*4}if(d<28)collect(l)}loot=loot.filter(l=>!l.gone);player.shield=Math.min(player.maxShield,player.shield+dt*2);if(player.hp<=0)die();}
function spawnEnemy(p){const t=p.type==='high'?'high':p.type==='mid'?'mid':'low';enemies.push({x:p.x+Math.random()*180-90,y:p.y+Math.random()*180-90,hp:t==='high'?70:t==='mid'?45:28,speed:t==='high'?95:t==='mid'?120:145,damage:t==='high'?18:12,type:t});}
function autoAttack(){let e=enemies.sort((a,b)=>Math.hypot(player.x-a.x,player.y-a.y)-Math.hypot(player.x-b.x,player.y-b.y))[0];if(!e)return;const a=Math.atan2(e.y-player.y,e.x-player.x);shots.push({x:player.x,y:player.y,vx:Math.cos(a)*620,vy:Math.sin(a)*620,life:1,damage:player.attack});}
function drop(e){loot.push({x:e.x,y:e.y,r:12,type:'coin',value:3},{x:e.x+18,y:e.y,r:12,type:'xp',value:28});if(Math.random()<.35)loot.push({x:e.x-16,y:e.y,r:12,type:'tech',value:1});}
function collect(l){l.gone=true;if(l.type==='coin')state.coins+=l.value;if(l.type==='tech')state.tech+=l.value;if(l.type==='xp'){state.xp+=l.value;if(state.xp>=100){state.xp-=100;state.level++;state.upgrade=true}}if(l.type==='black_box'){state.blackBoxRecovered=true;state.coins+=l.value;save.blackBoxes=(save.blackBoxes||0)+1;delete save.blackBox;persist()}}
function die(){state.mode='dead';state.dead=true;save.bestDay=Math.max(save.bestDay,Math.floor(state.day));save.bestKills=Math.max(save.bestKills,state.kills);save.blackBox={x:player.x,y:player.y,day:Math.floor(state.day),coins:Math.floor(state.coins*.5),weapon:'自动激光'};persist()}function persist(){localStorage.setItem(saveKey,JSON.stringify(save))}
function clickUi(x,y){if(state.upgrade){player.attack*=1.2;player.maxHp+=20;state.upgrade=false;return}if(state.mode==='dead'){start();return}if(state.dock){state.dock=false;return}if(state.dockPrompt&&x>innerWidth-190&&y>innerHeight-90){state.dock=true;player.hp=player.maxHp;return}}
function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);drawSpace();if(state.mode==='menu')return drawMenu();const cx=innerWidth/2-player.x,cy=innerHeight/2-player.y;for(const p of planets)drawPlanet(p,cx,cy);for(const l of loot)drawIcon(l.type,l.x+cx,l.y+cy,l.r*2);for(const e of enemies)drawEnemy(e,cx,cy);for(const s of shots){ctx.strokeStyle='#83f7ff';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(s.x+cx,s.y+cy);ctx.lineTo(s.x+cx-s.vx*.035,s.y+cy-s.vy*.035);ctx.stroke()}drawShip(innerWidth/2,innerHeight/2);drawHud();if(state.upgrade)panel('升级选择','激光伤害 +20%\n最大生命 +20\n点击任意位置继续');if(state.dock)panel('中立星球停靠','已修理飞船\n商店 / 升级 / 传送 / 文明图鉴 / 黑匣子坐标\n点击关闭');if(state.mode==='dead')panel('远征结束','存活 '+Math.floor(state.day)+' 天 · 击杀 '+state.kills+'\n已记录黑匣子坐标\n点击开始下一局');}
function drawSpace(){ctx.fillStyle='#06102d';ctx.fillRect(0,0,innerWidth,innerHeight);ctx.fillStyle='#fff';for(let i=0;i<90;i++){const x=(i*97+state.day*3)%innerWidth,y=(i*53)%innerHeight;ctx.globalAlpha=.25+(i%5)/10;ctx.beginPath();ctx.arc(x,y,i%3+1,0,7);ctx.fill()}ctx.globalAlpha=1;}
function drawMenu(){panel('迷失深空：远征者','Lost Deep Space: Drifter\n开始游戏 / 继续远征 / 永久升级 / 文明图鉴\n点击屏幕开始\nGitHub Pages: /space-game/');}
function drawShip(x,y){ctx.fillStyle='#67e8f9';ctx.strokeStyle='#082f49';ctx.lineWidth=5;ctx.beginPath();ctx.roundRect(x-22,y-28,44,56,18);ctx.fill();ctx.stroke();ctx.fillStyle='#fde68a';ctx.beginPath();ctx.arc(x,y-8,12,0,7);ctx.fill();ctx.stroke();}
function drawEnemy(e,cx,cy){drawIcon('enemy_'+e.type,e.x+cx,e.y+cy,42)}function drawPlanet(p,cx,cy){const x=p.x+cx,y=p.y+cy;drawIcon('planet_'+p.type,x,y,p.r*2);if(p.angry){ctx.strokeStyle='#fb7185';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,p.r+70,0,7);ctx.stroke()}}
function drawIcon(type,x,y,size){ctx.fillStyle=type.includes('coin')?'#facc15':type.includes('xp')?'#60a5fa':type.includes('tech')?'#a78bfa':type.includes('neutral')?'#86efac':'#fb7185';ctx.strokeStyle='#10213f';ctx.lineWidth=4;ctx.beginPath();ctx.arc(x,y,size/2,0,7);ctx.fill();ctx.stroke();}
function drawHud(){ctx.fillStyle='rgba(8,18,45,.78)';ctx.strokeStyle='#6ee7ff';ctx.lineWidth=2;ctx.roundRect(12,12,250,92,16);ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.font='15px sans-serif';ctx.fillText(`生命 ${Math.max(0,Math.floor(player.hp))}/${player.maxHp}  护盾 ${Math.floor(player.shield)}`,26,40);ctx.fillText(`等级 ${state.level}  XP ${state.xp}/100  金币 ${state.coins}`,26,66);ctx.fillText(`科技碎片 ${state.tech}`,26,90);ctx.textAlign='center';ctx.fillText(`存活第 ${Math.floor(state.day)} 天`,innerWidth/2,30);ctx.textAlign='left';ctx.fillStyle='rgba(8,18,45,.78)';ctx.roundRect(innerWidth-182,14,168,150,16);ctx.fill();ctx.fillStyle='#fff';ctx.fillText('小地图',innerWidth-164,38);ctx.fillStyle='#67e8f9';ctx.fillRect(innerWidth-100,85,6,6);for(const p of planets.slice(0,20)){const mx=innerWidth-98+(p.x-player.x)/60,my=88+(p.y-player.y)/60;if(mx>innerWidth-175&&mx<innerWidth-20&&my>48&&my<155){ctx.fillStyle=p.type==='neutral'?'#86efac':'#fca5a5';ctx.fillRect(mx,my,4,4)}}ctx.fillStyle='rgba(8,18,45,.78)';ctx.roundRect(innerWidth-210,180,196,190,16);ctx.fill();ctx.fillStyle='#fff';ctx.fillText('七大终极文明苏醒',innerWidth-196,205);CIVS.forEach((c,i)=>{ctx.fillText(`${c} ${Math.min(100,Math.floor(state.day/(3+i)*100))}%`,innerWidth-196,230+i*20)});ctx.fillText('武器：激光 导弹 无人机 护盾 EMP 黑洞',20,innerHeight-24);if(state.dockPrompt){ctx.fillStyle='#34d399';ctx.roundRect(innerWidth-190,innerHeight-82,170,54,18);ctx.fill();ctx.fillStyle='#06281d';ctx.fillText('停靠中立星球',innerWidth-160,innerHeight-50)}}
function panel(title,text){ctx.fillStyle='rgba(8,18,45,.92)';ctx.strokeStyle='#7dd3fc';ctx.lineWidth=4;ctx.roundRect(innerWidth/2-230,innerHeight/2-150,460,300,24);ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='24px sans-serif';ctx.fillText(title,innerWidth/2,innerHeight/2-96);ctx.font='16px sans-serif';text.split('\n').forEach((t,i)=>ctx.fillText(t,innerWidth/2,innerHeight/2-42+i*34));ctx.textAlign='left'}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
window.__LDSD_VERIFY__={state,start,step:(n=120)=>{for(let i=0;i<n;i++)update(1/60)},spawnEnemy:()=>spawnEnemy({x:player.x+90,y:player.y,type:'low'}),killOne:()=>{if(!enemies[0])spawnEnemy({x:player.x+50,y:player.y,type:'low'});enemies[0].hp=0;update(1/60)},dock:()=>{state.dockPrompt=true;state.dock=true},level:()=>{state.upgrade=true;state.level++},die,save,assets:ASSETS.map(imgUrl)};
